### ISSUE TITLE
Librelens Takeoff checklist

### ISSUE THREAD

**Issue by PhilippKuntschik** [LibreLens/lens#4]
- [X] create project
- [ ] automatically build binaries with github actions
- [ ] automatically detect new releases at lensapp/lens and create pull requests for this repository
- [ ] add new documentation to the repo
- [ ] test builds
  - [ ] mac
  - [ ] windows
  - [ ] ubuntu
- [ ] triage and fix detected issues
- [ ] check all (stale) branches if they are still needed
- [ ] create communications and documentation infrastructure
- [ ] create support workflows</div>

**Comment by jerch** [comment]
@PhilippKuntschik I wonder if librelens should see a major security overhaul as one of the early steps, like removing the overload/injection libs or even a partial downgrade. Can open a discussion, if you think it does not fit in this setup PR, to gain ppls attention and discuss ideas separately first (such a step would def. need some ppl with coding exp).

**Comment by techdragon** [comment]
I'll be testing the build once a mac binary is built and released. In the long term, maintenance works better with an organisation where more than one person has the keys. So i'm looking forward to switching over to this. Also if this is going to become a true fork, we probably want to look at renaming (_LibreLens_ seems suitable) since that will make it easier to get things like Homebrew and various linux package managers working once we have more things sorted out down the track.

**Comment by PhilippKuntschik** [comment]
@jerch, a security audit is a good idea, as soon as there are enough resources available. For this to happen, the project requires at least
- competencies in typescript security (or resources to have an independent audit).
- competencies in typescript development
- some people that help merging when a new upstream release is available.

I am also open to downgrade to any version. A discussion about which versions to support could happen in a separate issue. Would you initialize this?

@techdragon you are correct. I will update the checklist accordingly. A mac build should be available here: https://github.com/LibreLens/lens/releases/tag/v6.0.0 I opened a separate issue to collect any obstacle with the build: https://github.com/LibreLens/lens/issues/5

Right now, the packages are still unsigned since I miss the required infrastructure (an apple computer) and the development account. If someone has a "spare" apple developer account, please let me know.

**Comment by techdragon** [comment]
@PhilippKuntschik while its not really "spare" (since I use it) but I do have a personal Apple Developer account that I don't mind using to help out 😄

Github have documented things [pretty well](https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development#required-clean-up-on-self-hosted-runners) but I'd need the appropriate org/repo level membership/permissions to be able to safely edit the appropriate encrypted secrets to securely store the various necessary secret files and keys.

**Comment by PhilippKuntschik** [comment]
> @PhilippKuntschik while its not really "spare" (since I use it) but I do have a personal Apple Developer account that I don't mind using to help out smile
> 
> Github have documented things [pretty well](https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development#required-clean-up-on-self-hosted-runners) but I'd need the appropriate org/repo level membership/permissions to be able to safely edit the appropriate encrypted secrets to securely store the various necessary secret files and keys.

I sent you an invite for the organization. Give me a ping at librelens@philipp-kuntschik.de so that we could have a more direct sync. A big question that you may be able to answer is:

Does signing a package with your personal Apple Developer Account unalterably bind the project resources to your account? In other words: Does you signing the packages with your personal account forever require you to sign these packages? If so, I would argue that a more organizational approach is required.

**Comment by techdragon** [comment]
@PhilippKuntschik Thanks for that invite, I've accepted that just now. 

Since I've never needed the answer to that very relevant question I did some digging, and it has a slightly complicated answer unfortunately. There is no technical lock in tying the application to being signed by the same person/organisation... so yes it can be changed... however if the owner level identity of the signer changes, there is the potential for various APIs that check the value of the code signing identity, to throw up a warning to the user for the obvious reason that if this identity has changed without their knowledge someone may have swapped the app for a malicious version. ( Covered in part here -> https://developer.apple.com/forums/thread/669350 ) 

Since I wasn't opposed to sorting out the setup of a more formal "organisation" account to mitigate that problem, I decided to look into it, and it turns out to be quite a pain. In order to setup an organisation accounts that multiple developers can be invited to, share access to, replace certificates in future with another one setup by a different developer in the organisation without potential security warnings, Apple requires a DUNS number, which requires giving Dun & Bradstreet a pile of formal information like company names, phone numbers, and other such things... Effectively its "register as a business" territory. This is obviously an annoying situation for a random open source team to be in, and its been that way for half a decade ( see here ->  https://opensource.stackexchange.com/questions/5379/duns-signing-open-source-application ) 

So either a formal legal entity needs to be created to get a DUNS number and proceed with setting up a multi-developer Apple developer ID account, or the limitations inherent in using a single individual's Apple Developer ID to perform the code signing and notarisation needs to be accepted.

And I've replied with all this publicly in the issue here rather than via email since, if we do go down the path of using my Apple Developer ID it felt appropriate to keep the decision process as public as possible in the interest of giving anyone downloading the application being as much trust in the signed binary as possible and to help mitigate any future potential trust issues with a change over if later on months/years from now a more formal legal entity is setup to look after everything.

**Comment by PhilippKuntschik** [comment]
> And I've replied with all this publicly in the issue here rather than via email since, if we do go down the path of using my Apple Developer ID it felt appropriate to keep the decision process as public as possible in the interest of giving anyone downloading the application being as much trust in the signed binary as possible and to help mitigate any future potential trust issues with a change over if later on months/years from now a more formal legal entity is setup to look after everything.

That was exactly right. these things have to be discussed in public. I asked that specific question because we had a similar case back in the days when I developed android apps and we "lost" the signing certificate.

My "from the hip" train of thought would be the following: we rename the application to `librelens-beta` as to not block the forks name on the long-run and give it a go using a individual developer certificate. In case this project has to become the main open source package provider for lens, I would consider creating a legal entity like a "Verein" in German (something like club/association/foundation in english? basically a NPO) which controls the signing keys. Nonetheless, I would like to give this more thought until maybe next week. Thoughts from you?

**Comment by techdragon** [comment]
I think there's not a lot of risk that GitHub would "lose" the key data so it really just comes down to the potential issues around swapping the key in the future if that becomes _suddenly_ necessary, if its not suddenly necessary we could pre-warn users what to expect if we plan a key change in advance... and given the organisational complexity inherent getting a DUNS number and getting a multi-developer Apple Developer account setup... I think going the individual key is the right call for at least the time being. 

Longer term I think setting up as either a stand alone legal entity or as a "sub-project" of an existing open source associated legal entity (the term I'm familiar with for this sort of legal relationship is "auspicing") is definitely the right way to go. Once that legal entity situation is dealt with a DUNS number would either exist already or can be created, Apple stuff setup, and the signing key can be swapped for one that designates that organisation account as the primary identification, so any subsequent keys won't cause issues since having more than one person able to create signing keys would good from a maintenance point of view.

I'm not sure about the rename though, given the ability to give advanced warning (and the fact I can't actually find any example of what the macOS warning dialog popup from changing the signing key would look like, so I'm wondering how likely it is that a user will see a scary warning of some kind) it might be better to go ahead without the name change, but I don't have a strong feeling on this one and other than that calling it a "beta" might make it harder to get Homebrew package related stuff setup since they have some policies about forks, versioning, and naming https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask 

I definitely think your right @PhilippKuntschik about taking a little to think on it before making choices, the social/organisational stuff around forks, be they friendly or otherwise, are important enough we should definitely try and get it right. 

I would also welcome the thoughts from anyone else following long, this is meant to be a community focused fork after all.

**Comment by jerch** [comment]
> I am also open to downgrade to any version. A discussion about which versions to support could happen in a separate issue. Would you initialize this?

Currently to me it seems the overall sentiments are against such a step, which would include code reworks right from the beginning. I dont see other arguments into such a direction beside my own. From my perspective the need for a hardfork is an unavoidable step sooner or later (I think mirantis will work on making builds from their OSS repo harder, or even drop it completely in the future).

The lengthy discussions about easy deploy-able builds are ok and help to bridge to current rollout gap, but dont answer yet the pressing question of proper code maintenance in longer terms. For this we need at least a few coders, but I see no one else offering something in that regard. If we cannot get more peeps involved here, any "build-through repo with signed binary output" thingy is doomed to fail, once mirantis removed key functionality from their OSS repo,  lets say in 3 - 6 months.

While I think that this will happen, I am not keen to be the only one offering some coding and security reworks upfront. I think it is not worth yet to be discussed, unless we have more coders aboard. Which may never happen, or not before mirantis seriously cuts into the OSS functionality and we are stuck with aging code anyway. So currently thats a "no, not yet" from my side.

**Comment by PhilippKuntschik** [comment]
> I think there's not a lot of risk that GitHub would "lose" the key data so it really just comes down to the potential issues around swapping the key in the future if that becomes _suddenly_ necessary, if its not suddenly necessary we could pre-warn users what to expect if we plan a key change in advance... and given the organisational complexity inherent getting a DUNS number and getting a multi-developer Apple Developer account setup... I think going the individual key is the right call for at least the time being.
> 
> Longer term I think setting up as either a stand alone legal entity or as a "sub-project" of an existing open source associated legal entity (the term I'm familiar with for this sort of legal relationship is "auspicing") is definitely the right way to go. Once that legal entity situation is dealt with a DUNS number would either exist already or can be created, Apple stuff setup, and the signing key can be swapped for one that designates that organisation account as the primary identification, so any subsequent keys won't cause issues since having more than one person able to create signing keys would good from a maintenance point of view.
> 
> I'm not sure about the rename though, given the ability to give advanced warning (and the fact I can't actually find any example of what the macOS warning dialog popup from changing the signing key would look like, so I'm wondering how likely it is that a user will see a scary warning of some kind) it might be better to go ahead without the name change, but I don't have a strong feeling on this one and other than that calling it a "beta" might make it harder to get Homebrew package related stuff setup since they have some policies about forks, versioning, and naming https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask
> 
> I definitely think your right @PhilippKuntschik about taking a little to think on it before making choices, the social/organisational stuff around forks, be they friendly or otherwise, are important enough we should definitely try and get it right.
> 
> I would also welcome the thoughts from anyone else following long, this is meant to be a community focused fork after all.

Thank you @techdragon for your elaboration. You may have been able to silence my fears. The story with android back then played around the fact that its play store would never accept an app-update with a signing-key other than the one used to create the initial version of the app. If you lose that key, you can only delete the previous version of the app and initialize a new app. I realized that this is only peripherally our use case since the users would not install Lens from a store, but from github. Switching certificates could be resolved by the user removing the app from the system and installing the new version. 

You should have the required permissions to add secrets/certificates and to update the github workflows. If you feel confident in sharing your key for signing the binaries, you are free to do so.

**Comment by PhilippKuntschik** [comment]
> From my perspective the need for a hardfork is an unavoidable step sooner or later (I think mirantis will work on making builds from their OSS repo harder, or even drop it completely in the future).

Fully agree with you. Their announcement of a "web browser version" while the issue about OSS builds is not resolved made me think that they may move away from the installed version completely. I shudder thinking about the security implications of such a version, especially since I expect way to many cluster not utilizing RBAC at all. 

Creating this repo primarily has two goals for me: i) fully automating the necessary CI/CD workflows so that big chunks of work are already solved, once a real fork is necessary and ii) Getting a better overview and understanding of the code, its organization and its quality. It seems that they never removed any stale/merged/closed branch ever, which made exploring the tree a bit hard.
 
> ..
>  While I think that this will happen, I am not keen to be the only one offering some coding and security reworks upfront. I think it is not worth yet to be discussed, unless we have more coders aboard. Which may never happen, or not before mirantis seriously cuts into the OSS functionality and we are stuck with aging code anyway. So currently thats a "no, not yet" from my side.

Thank you for speaking freely. I don't blame you and I don't expect you to do anything at all. With regards to code reworks, I do not think there will happen much in the foreseeable future, since it is not the current goal of this repository. (I may solve some bugs if they really annoy me, though). I hope I can still count on your help by reporting any issue that you come across in the binaries.

**Comment by HaTiIn** [comment]
It would be nice if you add chocolatey support to your TODO list.
